name: publish

on: [push, workflow_dispatch]

jobs:
  default:
    name: etcdkeeper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          # passthrough CI into build container
          context: .
          file: Dockerfile
          load: false
          tags: ramir-savvy/etcdkeeper:latest
          push: true
